name: teller_connect
description: "Teller.io connect SDK for Flutter. Instantly connect your app to thousands of financial institutions"
version: 0.2.0
homepage: https://maxint.com

topics:
  - sdk
  - teller
  - openbanking

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  alfred: ^1.1.1
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  html: ^0.15.4
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.25.8

flutter:
  assets:
    - assets/web/

platforms:
  android:
  ios:
  web:
  linux:
  macos:
  windows:
